### ISSUE TITLE
New Feature: Litter Tracking

### ISSUE THREAD

**Issue by kylelambert101** [kylelambert101/Meow#1]
Implement a page for tracking litter cleaning

_Prerequisite: Backend for storing persistent history of cleanings_

- [ ] Present button to indicate that a cleaning was done today
- [ ] Display the last-performed cleaning at the top of the page
- [ ] Display the next-needed cleaning (three days from last performed) at the top of the page
