### ISSUE TITLE
New Feature: Food Tracking

### ISSUE THREAD

**Issue by kylelambert101** [kylelambert101/Meow#2]
Implement a page for tracking feedings and food stock

_Prerequisite: Backend for persistent storage of food information_

- [ ] Button to indicate that a feeding occurred
- [ ] Picker for selecting when feedings should occur
- [ ] Gauge showing how much food is left
- [ ] Indicator of how many days are left with existing food stock
- [ ] Dialog for new food purchases (capture how much food to add to stock)
